# Generated by Django 5.0.6 on 2024-06-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TennisPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("nationality", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("racket_brand", models.CharField(max_length=100)),
                ("racket_model", models.CharField(max_length=100)),
            ],
        ),
    ]
