name: Run Tests

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:
    tests:
        runs-on:
            - ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
        
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'
            
            - name: Setup PDM
              uses: pdm-project/setup-pdm@v3 
              with:
                python-version: '3.11'
                cache: 'true'

            - name: Install dependencies
              run: pdm install
        
            - name: Run code formatting check
              run: pdm run check_code_format

            - name: Run CalculatorApp test
              run: pdm run test_calculator

            - name: Run Main App tests
              run: pdm run tests
              
            - name: Run coverage report
              run: pdm run coverage_report
        